name: Break Glass Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy.yml@main
    with:
      environment: STAGING-${{ github.event.inputs.environment }}

  test-staging:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run End-to-End Test
        uses: ./composite-actions/end-to-end-test
        with:
          environment: STAGING-${{ github.event.inputs.environment }}

  deploy-prod:
    uses: ./.github/workflows/deploy.yml@main
    needs:
      - test-staging
    with:
      environment: PROD-${{ github.event.inputs.environment }}

  test-prod:
    runs-on: ubuntu-latest
    needs: deploy-prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run End-to-End Test
        uses: ./composite-actions/end-to-end-test
        with:
          environment: PROD-${{ github.event.inputs.environment }}
