name: Template - Deploy environment

on:
  workflow_call:
    inputs:
      workflow_file:
        required: true
        type: string
      gh_token:
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  execute-workflow:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute provided workflow
        run: |
          echo "Executing workflow from file: ${{ inputs.workflow_file }}"
          gh workflow run ${{ inputs.workflow_file }}